apiVersion: v1
kind: Service
metadata:
  name: navidrome-service
  namespace: music
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: navidrome
  ports:
    - protocol: TCP
      port: 4533
      targetPort: 4533
